### ISSUE TITLE
bug: argus seems to not close url connections on latest / deployed versions check.

### ISSUE THREAD

**Issue by jrhbcn** [release-argus/Argus#153]
**Describe the bug**
Argus seems to leave open url connections. I am using the software [webhook](https://github.com/adnanh/webhook) to serve hooks for argus to check deployed versions. After a while (2-3 days) webhook hangs with "too many open files" and no more hooks respond. Re-starting argus fixes the problem. This comes from an initial webhook issue [#602](https://github.com/adnanh/webhook/issues/602).
. 
**To Reproduce**
I am using argus with loads (around 40) services and most of them use webhook urls to find the deployed and latest versions. My config for services looks like:

 ```
 Plex:
    options:
      semantic_versioning: false
    latest_version:
      type: url
      url: http://192.168.1.10:7000/hooks/version-latest?name=plex
      url_commands:
        - type: regex
          regex: ([0-9.]+)
    deployed_version:
      url: http://192.168.1.10:7000/hooks/version-deployed?name=plex
      json: version
    notify:
      telegram_info: {}
    webhook:
      update_docker:
        url: http://192.168.1.10:7000/hooks/update-docker?container=plex
    dashboard:
      icon: https://github.com/walkxhub/dashboard-icons/raw/master/png/plex.png
      web_url: https://forums.plex.tv/t/plex-media-server/30447/1502
```

[webhook](https://github.com/adnanh/webhook) is running on machine 192.168.1.10. Running the url for `http://192.168.1.10:7000/hooks/version-deployed?name=plex` returns the string `{"name":"plex","version":"1.28.2.6151"}`. Running it for `http://192.168.1.10:7000/hooks/version-latest?name=plex` returns the string `1.28.2.6151`. Everything works fine on first execution. After 2-3 days webhook starts complaining of "too many open files" and hangs. Re-starting argus fixes the problem. For instance, see this output with 1211500 as webhook pid number: 

```
# ls -l /proc/1211500/fd | wc -l
1025
# docker-compose stop argus
Stopping argus ... done
# ls -l /proc/1211500/fd | wc -l
9
# docker-compose up -d argus
Starting argus ... done
# ls -l /proc/1211500/fd | wc -l
17
```

**Expected behavior**
Argus closes url connections?

**Version:**
 Using argus 0.10.1 container from ghcr.io/release-argus/argus:latest

**Comment by JosephKav** [comment]
Ah, looks like I'm not closing the connection with
> defer resp.Body.close

on the latest and deployed version queries! I'll re-add them now and release a patch that should solve this issue. Sorry you've spent so much time looking into this, but thanks for doing that and reporting it :smile:

**Comment by jrhbcn** [comment]
Sorry to bother you again with this @JosephKav. Are you sure all connections are closed? I am still experiencing problems with this (even though it seems to be increasing much slower than before):

```
# ls -l /proc/1211500/fd | wc -l
375
# docker-compose stop argus
# ls -l /proc/1211500/fd | wc -l
7
```

Regards,

**Comment by JosephKav** [comment]
As far as I can see, I am closing them. Are you definitely on the latest version? I have two servers that have been running `0.10.2` since I released it last Tuesday and their fd's are at 12 and 14 :/. What do you have Argus monitoring, only latest versions, or deployed as well. Does it send any notifications/webhooks?

**Comment by jrhbcn** [comment]
> As far as I can see, it is closing them. Are you definitely on the latest version? 

Yes, the status page shows this:
![image](https://user-images.githubusercontent.com/22198270/190337500-2f7642f3-25c7-45c8-ab61-9d5b66129b7f.png)

> I have two servers that have been running `0.10.2` since I released it last Tuesday and their fd's are at 12 and 14 :/. What do you have Argus monitoring, only latest versions, or deployed as well. 

I am monitoring both latest and deployed versions using calls to webhook (see an example config of the plex service before). Also I am using webhooks also to update docker containers. However, I don't use that often but could be the problem?

```
webhook:
  update_docker:
    type: github
    url: http://192.168.1.10:7000/hooks/update-docker?container=name
    secret: mysecret
```

> Does it send any notifications/webhooks?

I am using telegram for notifications (they work fine) and the webhooks I've shown above. Again, thanks for looking into this!

**Comment by JosephKav** [comment]
Alright, thanks.
Looking into this briefly just now I found [this](http://craigwickesser.com/2015/01/golang-http-to-many-open-files/) that may explain the problem.
I have Argus sending Telegram and other notifications as well as webhooks to an AWX server. I think the issue *could* be with the webhook server you've got for latest/deployed versions not setting the header to close the connection. (Mine only use GitHub/official URLs).
I'll do a PR shortly to add this header

> A significant difference between HTTP/1.1 and earlier versions of HTTP is that persistent connections are the default behavior of any HTTP connection.

**Comment by jrhbcn** [comment]
I am not using any server in between, [webhook](https://github.com/adnanh/webhook) runs in the same computer as argus docker is running.  I am going to try your changes and report back any findings!

**Comment by jrhbcn** [comment]
@JosephKav I think you finally fixed it. Running latest master version now. The number of files opened by webhook remains constant in 7 (and just going up when versions are checked and then going down again). I am going to see if this stays like this for a few days, but it does look like fixed already. Thanks!
