### ISSUE TITLE
Question:  Is it possible to replace a character in the regex match

### ISSUE THREAD

**Issue by samcro1967** [release-argus/Argus#269]
I have a service that lists the current version using a dash on Github and a plus sign in the app.  Trying to figure out how to swap the character in regex and am not having any luck.  Is this even possible?

Here is what I tried.
```
ReplaceAllString('([0-9.]+\+[0-9a-z]+)', '$1\-$2', $string)
```

![image](https://github.com/release-argus/Argus/assets/2319445/b60c0eee-b96e-41e6-8a5c-dbd301915993)

**Comment by JosephKav** [comment]
You could make it non-semantic versioning and replace `-rc` with `+rc`, so the latest will match the deployed style

**Comment by samcro1967** [comment]
ReplaceAllString is failing, but could be related to the semantic_versioning issue?

![image](https://github.com/release-argus/Argus/assets/2319445/529668b4-3998-4f2e-afcc-95cb84920df3)

**Comment by JosephKav** [comment]
Yeah, looks like it could be based on it saying `$string)semantic_versioning=`. Looks like it's defaulted `false` to `""`, and missed out the `&` to separate the 'semantic_versioning' value. Both of these should be fixed in [this PR](https://github.com/release-argus/Argus/pull/270) that i'm merging now

**Comment by samcro1967** [comment]
Still not working.  I just truncated the version to 1.20.0 on both deployed and latest and called it a day.  :-)
